### PR TITLE
Manual Siren

### PR DESCRIPTION
**Pull request by termanator1128**

### CODE REVIEW

**Comment by termanator1128** [comment]
Fixed. And manual siren needs to be able to be done with all stages

**Comment by Jacob-Developing03** [comment]
.0

**Comment by MrDaGree** [comment]
does sirens that stay on conflict? How does that work with the manual sirens?

**Comment by termanator1128** [comment]
The only thing is that you can't run the horn and manual siren at the same time but other than that I haven't had any other issues.

**Pull request closed without merging**
