### PR TITLE
Minor performance improvements

### PR DESCRIPTION
**Pull request by ElPumpo**
This pr contains minor improvements to improve performance, for example saving variables where applicable to speed up stuff.

Also enforce 4 tab indent, end added an editorconfig file.

### CODE REVIEW

**Comment by ElPumpo** [comment]
Should also mention I've tested all my changes, but I'm not 100% if I broke anything, so you should really test the full code.. again before merging the pr. Btw z you alive?

**Comment by ElPumpo** [comment]
You'll find this PR in the garbage bin

**Comment by Zeemahh** [comment]
> You'll find this PR in the garbage bin

ok

**Comment by Zeemahh** [comment]
RIP at not submitting review, though I still don't see why you closed this. I was busy with other things, hence the delay.

**Pull request closed without merging**
