### PR TITLE
Performance updates!

### PR DESCRIPTION
**Pull request by JHodgson1**
In this PR I've addressed some issues which caused a large delay with executing the code (~1msec /frame(or tick) without lights).

- Performance
   - Add a 500msec loop which updates important information, such as.
      - Is the vehicle ELS and in the table?
      - Is the ped able to control the lights?
      - Some more, I forgot :P ...
   - Replace every tick checks which were performance heavy, included doing the aforementioned improved things every tick - no good :(

### CODE REVIEW

**Comment by MrDaGree** [comment]
Performance Updates

**Comment by JHodgson1** [comment]
Oh, this was a draft because I was still looking for things to improve :P

**Comment by MrDaGree** [comment]
lol I wanted it in ASAP due to the performance stuff. I dont mind merging multiple PR's if you keep making them

**Comment by MrDaGree** [comment]
rip. I messed it up now. Im sorry thats probs going to cause problems for you.

**Pull request merged**
